Easy_finder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('homepage');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//conform and pendding
Route::post('/bechelor_confirm/{bechelor_confirm}/completed', [
    'uses' => 'BechelorBookingController@completed',
    'as' => 'bechelor_confirm.completed'
]);//hello every one

Route::middleware(['auth'])->group(function () {

	Route::resource('bechelor_room','Bechelor_RoomController');
	Route::resource('comment','BechelorCommentController');
	Route::resource('profile','ProfileController');
	Route::resource('booking','BechelorBookingController');

});

//bechelor Booking route
Route::get('/bechelor/{bechelor}/booking', [
    'uses' => 'BechelorBookingController@booking',
    'as' => 'bechelor.booking'
]);

Route::get('/cities/ajax/{id}', [
	'uses' => 'Bechelor_RoomController@cities_ajax',
	'as' => 'cities'
]);

Route::get('/thanas/ajax/{id}', [
	'uses' => 'Bechelor_RoomController@thanas_ajax',
	'as' => 'thanas'
]);


//search city ,thana and ward
Route::get('/search', [
	'uses' => 'ThanaController@search',
	'as' => 'search'
]);
// 
Route::post('/search_post/search_post', [
	'uses' => 'ThanaController@search_post',
	'as' => 'search_post.search_post'
]);

//using thana id show ....

Route::get('/bechelor/show/{id}', [
	'uses' => 'ThanaController@show',
	'as' => 'bechelor.show'
]);
// show post using user id 
Route::get('/bechelor_post/by_user_id/{id}', [
	'uses' => 'ProfileController@by_user_id',
	'as' => 'bechelor_post.by_user_id'
]);


//user_booking
Route::get('/bechelor_booking/user_booking/{id}', [
	'uses' => 'BechelorBookingController@user_booking',
	'as' => 'bechelor_booking.user_booking'
]);


//
Route::get('/room_details/room_details/{id}', [
	'uses' => 'Bechelor_RoomController@room_details',
	'as' => 'room_details.room_details'
]);

//show Request
Route::get('/show_request/show_request/{id}', [
	'uses' => 'BechelorBookingController@show_request',
	'as' => 'show_request.show_request'
]);

//user details 
Route::get('/user_details/show/{id}', [
	'uses' => 'HomeController@user_show',
	'as' => 'user_details.show'
]);

Easy_finder/app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    //
}

Easy_finder/app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Thana;
use App\Bechelor_Room;
use App\BechelorComment;
use App\User;

class ProfileController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    //MY POST 
    public function by_user_id($id){
        //dd($id);
        $bechelor_room = Bechelor_Room::where('user_id', $id)->get();
        //dd($bechelor_room);
        $thanas = Thana::all();
        $comments=BechelorComment::all();
        return view('Bechelor_room.index', compact('bechelor_room', 'thanas','comments'));
    }

    //
    public function index()
    {
        return view('Profiles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    public function upload($file){
        $name =time().$file->getClientOriginalName();
        $filename=$name;
        $current = public_path('profile_images/');
        $file->move($current, $filename);
        return 'profile_images/'.$filename;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::findOrFail($id);
        return view('Profiles.edit',compact('users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $this->validate($request, [
        //     "name"=>"required",
        //     "email"=>"required",
        //     "password"=>"required",
        //     "gender"=>"required",
        //     "date_of_birth"=>"required",
        //     "religion"=>"required",
        //     "national_id"=>"required",
        //     "mobile"=>"required",
        //     "image"=>"required",
        //     "address"=>"required"
        // ]);
        $users = User::findOrFail($id);
        $input =$request->all();
        if(isset($input['image'])){
            $input['image'] = $this->upload($input['image']);
        }
        $result=$users->update($input);
        if($result){
            return redirect('profile')->with('message','Profile update Successful');
        }else{
            return beck()->with('message','Some Error Occar');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

Easy_finder/resources/views/Profiles/edit.blade.php
@extends('layouts.app')
@section('content')
  <script type="text/javascript" src="{{ url('')}}/assets/js/jquery-3.2.1.min.js"></script>
  <div class="content">
    <div class="animated fadeIn">
      <div class="row">
        <div class="col-xs-8 col-sm-8 col-md-8">
          @if((Session::get('message')))
          <div class="alert alert-success alert-dismissable">
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ Session::get('message')}}
            </div>
          </div>
          @endif
          <div class="card">
            <div class="card-header" style="text-align: center; background-color: #0321fd; color: #ffffff">
              <strong>Bechelor Room Create/Post Form</strong>
            </div>
            <div class="card-body card-block">
                            <div class="col-sm-4 " style="margin-top: 120px">
                                @if($users->image!="")
                                <img src="{{asset($users->image)}}" alt="Card image cap" width="" height="">
                                @endif
                            </div>
                            <div class="col-sm-8">
                                <form class="form-horizontal" method="POST" action="{{ route('profile.update',$users->id) }}" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    {{method_field('PUT')}}
                                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                        <label for="name" class="col-md-4 control-label">Name</label>
                                        <div class="col-md-12">
                                            <div class="input-group">
                                                <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                                                <input id="name" type="text" class="form-control" name="name" value="{{$users->name}}">
                                                @if ($errors->has('name'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('name') }}</strong>
                                                </span>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('gender') ? ' has-error' : '' }}">
                                        <label for="gender" class="col-md-4 control-label">Gender</label>
                                        <div class="col-md-12">
                                            <div class="input-group">
                                                <div class="input-group-addon"><span class="glyphicon glyphicon-king"></span>
                                                <input  type="radio" name="gender" value="male" @if($users->gender=='male') checked @endif>Male</div>
                                                <div class="input-group-addon"><span class="glyphicon glyphicon-king"></span>
                                                <input type="radio" name="gender" value="female" @if($users->gender=='female') checked @endif>Female</div>
                                                <div class="input-group-addon"><span class="glyphicon glyphicon-king"></span>
                                                <input type="radio" name="gender" value="other" @if($users->gender=='other') checked @endif>Other</div>
                                                @if ($errors->has('gender'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('gender') }}</strong>
                                                </span>
                                                @endif
                                           </div>
                                       </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('date_of_birth') ? ' has-error' : '' }}">
                                        <label for="date_of_birth" class="col-md-4 control-label">Date of Birth</label>
                                        <div class="col-md-12">
                                            <div class="input-group">
                                        <div class="input-group-addon"><span class="glyphicon glyphicon-eye-open"></span></div>
                                            <input id="datepicker" type="text" class="form-control" name="date_of_birth" value="{{ $users->date_of_birth }}">
                                            @if ($errors->has('date_of_birth'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('date_of_birth') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                    </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('religion') ? ' has-error' : '' }}">
                                        <label for="religion" class="col-md-4 control-label">Religion</label>
                                        <div class="col-md-12">
                                            <div class="input-group">
                                        <div class="input-group-addon"><span class="glyphicon glyphicon-heart"></span></div>
                                            <select name="religion" id="religion" class="form-control">
                                                <option value="0" disabled="true" selected="true">===Choose Religion===</option>
                                                <option value="Islam" @if ($users->religion == "Islam")selected="selected" @endif >Islam</option>
                                                <option value="Hinduism" @if ($users->religion == "Hinduism")selected="selected" @endif >Hinduism</option>
                                                <option value="Buddhism" @if ($users->religion == "Buddhism")selected="selected" @endif >Buddhism</option>
                                                <option value="Christianity" @if ($users->religion == "Christianity")selected="selected" @endif >Christianity</option>
                                            </select>
                                            @if ($errors->has('religion'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('religion') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('national_id') ? ' has-error' : '' }}">
                                        <label for="national_id" class="col-md-4 control-label">National Id</label>
                                        <div class="col-md-12">
                                            <div class="input-group">
                                        <div class="input-group-addon"><span class="glyphicon glyphicon-certificate"></span></div>
                                            <input id="national_id" type="number" class="form-control" name="national_id" value="{{ $users->national_id }}">
                                            @if ($errors->has('national_id'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('national_id') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('mobile') ? ' has-error' : '' }}">
                                        <label for="mobile" class="col-md-4 control-label">Mobile</label>
                                        <div class="col-md-12">
                                            <div class="input-group">
                                        <div class="input-group-addon"><span class="glyphicon glyphicon-phone-alt"></span></div>
                                            <input id="mobile" type="number" class="form-control" name="mobile" value="{{ $users->mobile }}">
                                            @if ($errors->has('mobile'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('mobile') }}</strong>
                                            </span>
                                            @endif
                                        </div>
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                                        <label for="image" class="col-md-4 control-label">Image</label>
                                        <div class="col-md-12">
                                            <div class="input-group">
                                                <div class="input-group-addon"><span class="glyphicon glyphicon-phone-alt"></span></div>
                                                <input id="image" type="file" class="form-control" name="image" value="{{ old('image') }}">
                                                @if ($errors->has('image'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('image') }}</strong>
                                                </span>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                                        <label for="address" class="col-md-4 control-label">Address</label>
                                        <div class="col-md-12">
                                            <div class="input-group">
                                                <div class="input-group-addon"><span class="glyphicon glyphicon-phone-alt"></span></div>
                                                <textarea name="address" id="address" class="form-control" cols="30" rows="5" value="">{{ $users->address }}</textarea>
                                                @if ($errors->has('address'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('address') }}</strong>
                                                </span>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-sm">Update</button>
                                    </form>
                     </div>
          </div>
        </div>
      </div>
  </div>
</div>
@endsection

Easy_finder/resources/views/Profiles/index.blade.php
@extends('layouts.app')
@section('content')
<div class="content">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        @if((Session::get('message')))
            <div class="alert alert-success alert-dismissable">
              <div class="alert alert-success alert-dismissable">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  {{ Session::get('message')}}
              </div>
            </div>
        @endif
        <div class="card">
          <div class="card-header">
            <strong class="card-title mb-3">Profile</strong>
          </div>
          <div class="row">
            <div class="col-sm-4">
              
              @if(Auth::user()->image!="")
                    <img src="{{asset(Auth::user()->image)}}" alt="Card image cap" width="200px" height="280px">
              @endif
              <span class="pull-right" style="margin-top: 20px"><a href="{{route('profile.edit', Auth::user()->id)}}" class="btn btn-warning btn-sm">Edit</a></span>

            </div>
            <div class="col-sm-3">
              <h4><span>Name:</span></h4><hr>
              <h4><span>Email:</span></h4><hr>
              <h4><span>Gender:</span></h4><hr>
              <h4><span>National ID:</span></h4><hr>
              <h4><span>Religion</span></h4><hr>
              <h4><span>Date Of Birth</span></h4><hr>
              <h4><span>Contact</span></h4><hr>
              <h4><span>Address</span></h4><hr>
            </div>
            <div class="col-sm-5">
              <h4><span>{{Auth::user()->name}}</span></h4><hr>
              <h4><span>{{Auth::user()->email}}</span></h4><hr>
              <h4><span>{{Auth::user()->gender}}</span></h4><hr>
              <h4><span>{{Auth::user()->national_id}}</span></h4><hr>
              <h4><span>{{Auth::user()->religion}}</span></h4><hr>
              <h4><span>{{Auth::user()->date_of_birth}}</span></h4><hr>
              <h4><span>{{Auth::user()->mobile}}</span></h4><hr>
              <h4><span>{{Auth::user()->address}}</span></h4><hr>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

Easy_finder/resources/views/Profiles/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div class="card">
        <div class="card-header">
          <strong class="card-title pl-2">Profile</strong><span class="pull-right">Back</span>
        </div>
        <div class="card-body">
          <div class="mx-auto d-block">
            <div class="row">
              <div class="col-sm-4">
                <img  src="{{asset($users->image)}}" height="400px" width="500px" alt="">
              </div>
              <div class="col-sm-3">
                <h4><span>Name:</span></h4><hr>
                <h4><span>Email:</span></h4><hr>
                <h4><span>Gender:</span></h4><hr>
                <h4><span>National ID:</span></h4><hr>
                <h4><span>Religion</span></h4><hr>
                <h4><span>Date Of Birth</span></h4><hr>
                <h4><span>Contact</span></h4><hr>
                <h4><span>Address</span></h4><hr>
              </div>
              <div class="col-sm-5">
                <h4><span>{{$users->name}}</span></h4><hr>
                <h4><span>{{$users->email}}</span></h4><hr>
                <h4><span>{{$users->gender}}</span></h4><hr>
                <h4><span>{{$users->national_id}}</span></h4><hr>
                <h4><span>{{$users->religion}}</span></h4><hr>
                <h4><span>{{$users->date_of_birth}}</span></h4><hr>
                <h4><span>{{$users->mobile}}</span></h4><hr>
                <h4><span>{{$users->address}}</span></h4><hr>
              </div>
            </div>
          </div>
          <hr>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection