Easy_finder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('homepage');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//conform and pendding
Route::post('/bechelor_confirm/{bechelor_confirm}/completed', [
    'uses' => 'BechelorBookingController@completed',
    'as' => 'bechelor_confirm.completed'
]);//hello every one

Route::middleware(['auth'])->group(function () {

	Route::resource('bechelor_room','Bechelor_RoomController');
	Route::resource('comment','BechelorCommentController');
	Route::resource('profile','ProfileController');
	Route::resource('booking','BechelorBookingController');

});

//bechelor Booking route
Route::get('/bechelor/{bechelor}/booking', [
    'uses' => 'BechelorBookingController@booking',
    'as' => 'bechelor.booking'
]);

Route::get('/cities/ajax/{id}', [
	'uses' => 'Bechelor_RoomController@cities_ajax',
	'as' => 'cities'
]);

Route::get('/thanas/ajax/{id}', [
	'uses' => 'Bechelor_RoomController@thanas_ajax',
	'as' => 'thanas'
]);


//search city ,thana and ward
Route::get('/search', [
	'uses' => 'ThanaController@search',
	'as' => 'search'
]);
// 
Route::post('/search_post/search_post', [
	'uses' => 'ThanaController@search_post',
	'as' => 'search_post.search_post'
]);

//using thana id show ....

Route::get('/bechelor/show/{id}', [
	'uses' => 'ThanaController@show',
	'as' => 'bechelor.show'
]);
// show post using user id 
Route::get('/bechelor_post/by_user_id/{id}', [
	'uses' => 'ProfileController@by_user_id',
	'as' => 'bechelor_post.by_user_id'
]);


//user_booking
Route::get('/bechelor_booking/user_booking/{id}', [
	'uses' => 'BechelorBookingController@user_booking',
	'as' => 'bechelor_booking.user_booking'
]);


//
Route::get('/room_details/room_details/{id}', [
	'uses' => 'Bechelor_RoomController@room_details',
	'as' => 'room_details.room_details'
]);

//show Request
Route::get('/show_request/show_request/{id}', [
	'uses' => 'BechelorBookingController@show_request',
	'as' => 'show_request.show_request'
]);

//user details 
Route::get('/user_details/show/{id}', [
	'uses' => 'HomeController@user_show',
	'as' => 'user_details.show'
]);

Easy_finder/resources/views/Bookers/create.blade.php
@extends('layouts.app')
@section('content')
  <script type="text/javascript" src="{{ url('')}}/assets/js/jquery-3.2.1.min.js"></script>
  <div class="content">
    <div class="animated fadeIn">
      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 offset-xs-3 offset-sm-3 offset-md-3">
          @if((Session::get('message')))
          <div class="alert alert-success alert-dismissable">
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ Session::get('message')}}
            </div>
          </div>
          @endif
          <div class="card">
            <div class="card-header" style="text-align: center; background-color: #0321fd; color: #ffffff">
              <strong>Bechelor Room Create/Post Form</strong>
            </div>
            <div class="card-body card-block">
                <form role="form" action="{{ route('booking.store')}}" method="post" enctype="multipart/form-data">
	                {{ csrf_field()}}
	                <input type="hidden" name="bechelor_room_id" value="{{$bechelor_booking->id}}">
	                <div class="form-group">
		                <label>How Many Seats You Can Comform</label>
		                <select name="seat" id="seat" class="form-control" required>
			                <option value="0" disabled="true" selected="true">===Choose Seat===</option>
			                <option value="1">1 Seat</option>
			                <option value="2" >2 Seat</option>
			                <option value="3" >3 Seat</option>
			                <option value="4" >4 Seat</option>
			                <option value="5" >5 Seat</option>
			                <option value="6" >6 Seat</option>
			                <option value="7" >7 Seat</option>
			                <option value="8" >8 Seat</option>
		                  </select>
		                  <small style="color: red">Please Select less than or equal to {{$bechelor_booking->seat}} Seats</small>
		                  <p class="help-block">{{ ($errors->has('seat')) ? $errors->first('seat') : ''}}</p>
	                </div>
	                <button type="submit" class="btn btn-primary">Book Confirm</button>
	            </form>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
@endsection

Easy_finder/resources/views/Bookers/edit.blade.php
edit.blade.php

Easy_finder/resources/views/Bookers/index.blade.php
@extends('layouts.app')
@section('content')

@foreach($booking as $post)
 <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="box-title">
                                    <h4 style="text-align: center;color:#fff;font-size: 40px;background-color: #0321fd;">Booking Information</h4>
                                    <span class="pull-right" style="margin-top: 5px"><input type="button" value="Print" onClick="window.print()"></span>
                                </h4>
                            </div>
                            <div class="row">
                                <div class="col-lg-6" >
                                    <div class="card-body">
                                        @if($post->bechelor_bookings->image!="")
                                        <div class="portfolio-item">
                                            <div class="portfolio-item-inner">
                                                <img class="img-responsive" src="{{asset($post->bechelor_bookings->image)}}" alt="">
                                                <div class="portfolio-info">
                                                    <a class="preview" href="{{asset($post->bechelor_bookings->image)}}" rel="prettyPhoto"><i class="fa fa-eye"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                        @endif

                                        @if(Auth::user()->email==$post->bechelor_bookings->user->email)
                                            <form method="post" action="{{ route('bechelor_confirm.completed',$post->id) }}">
                                            {{ csrf_field()}}
                                            <input type="hidden" name="bechelor_room_id" value="{{$post->bechelor_bookings->id}}">
                                                 <button type="submit" class="btn btn-primary btn-sm" style="margin-top: 5px">{{$post->status==true? 'Mark Pending':'Mark Confirm'}}</button>
                                            </form>
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="card-body">
                                        <div class="col-sm-12">
                                            <h4>Dear,<a href="{{route('user_details.show', $post->user->id)}}">{{$post->user->name}}</a><span class="pull-right" style="text-align: center;color: red">Date: {{$post->created_at->toFormattedDateString()}}</span></h3><hr>
                                            <h4>Congratulations,You have to request {{$post->seat}} seat for you.Now it's pendding,please contact match insearch and quary all information on this Seat.Seat is choosen by you please advance your seat money.Wait until confirm. <hr>
                                            <span>My name is {{$post->bechelor_bookings->user->name}}.I am match insearch.If Any Quary {{$post->bechelor_bookings->user->mobile}}.</span></h4><hr>

                                            <span>Total Seat</span><span class="pull-right">{{$post->seat}}</span><br>
                                            <span>Total Seat Rent</span><span class="pull-right">{{$post->room_rent}}</span>


                                            <p style="margin-top: 20px">
                                            <span class="btn btn-success btn-sm">{{$post->status == false?'Pendding':'confirm'}}</span>
                                            <span class="pull-right btn btn-warning btn-sm"><a href="{{route('room_details.room_details',$post->bechelor_bookings->id)}}">Room Details</a></span></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body"></div>
                        </div>
                    </div>
                </div>
@endforeach
@endsection