Easy_finder/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('homepage');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//conform and pendding
Route::post('/bechelor_confirm/{bechelor_confirm}/completed', [
    'uses' => 'BechelorBookingController@completed',
    'as' => 'bechelor_confirm.completed'
]);//hello every one

Route::middleware(['auth'])->group(function () {

	Route::resource('bechelor_room','Bechelor_RoomController');
	Route::resource('comment','BechelorCommentController');
	Route::resource('profile','ProfileController');
	Route::resource('booking','BechelorBookingController');

});

//bechelor Booking route
Route::get('/bechelor/{bechelor}/booking', [
    'uses' => 'BechelorBookingController@booking',
    'as' => 'bechelor.booking'
]);

Route::get('/cities/ajax/{id}', [
	'uses' => 'Bechelor_RoomController@cities_ajax',
	'as' => 'cities'
]);

Route::get('/thanas/ajax/{id}', [
	'uses' => 'Bechelor_RoomController@thanas_ajax',
	'as' => 'thanas'
]);


//search city ,thana and ward
Route::get('/search', [
	'uses' => 'ThanaController@search',
	'as' => 'search'
]);
// 
Route::post('/search_post/search_post', [
	'uses' => 'ThanaController@search_post',
	'as' => 'search_post.search_post'
]);

//using thana id show ....

Route::get('/bechelor/show/{id}', [
	'uses' => 'ThanaController@show',
	'as' => 'bechelor.show'
]);
// show post using user id 
Route::get('/bechelor_post/by_user_id/{id}', [
	'uses' => 'ProfileController@by_user_id',
	'as' => 'bechelor_post.by_user_id'
]);


//user_booking
Route::get('/bechelor_booking/user_booking/{id}', [
	'uses' => 'BechelorBookingController@user_booking',
	'as' => 'bechelor_booking.user_booking'
]);


//
Route::get('/room_details/room_details/{id}', [
	'uses' => 'Bechelor_RoomController@room_details',
	'as' => 'room_details.room_details'
]);

//show Request
Route::get('/show_request/show_request/{id}', [
	'uses' => 'BechelorBookingController@show_request',
	'as' => 'show_request.show_request'
]);

//user details 
Route::get('/user_details/show/{id}', [
	'uses' => 'HomeController@user_show',
	'as' => 'user_details.show'
]);

Easy_finder/app/Bechelor_Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bechelor_Room extends Model
{
	protected $table="bechelor__rooms";
    protected $fillable= ['date', 'status', 'gender', 'religion', 'married', 'room','seat', 'room_type', 'room_rent', 'image', 'facilities', 'conditions','mobile', 'city', 'thana', 'ward', 'address', 'user_id'];

    public function user(){
    	return $this->belongsTo('App\User');
    }


    public function cities()
    {
        return $this->belongsTo('App\City', 'city');
    }

    public function thanas(){
    	return $this->belongsTo('App\Thana','thana');
    }

    public function wards(){
    	return $this->belongsTo('App\Ward','ward');
    }
}

Easy_finder/app/Http/Controllers/Bechelor_RoomController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\City;
use App\Ward;
use App\Thana;
use Illuminate\Support\Facades\Auth;
use App\Bechelor_Room;
use App\BechelorComment;
use DB;

class Bechelor_RoomController extends Controller
{

    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bechelor_room=Bechelor_Room::orderBy('id','desc')->get();
        $comments=BechelorComment::all();
        //dd($comments);
        return view('Bechelor_room.index',compact('bechelor_room','comments'));
    }

    public function room_details($id){
        $bechelor_room = Bechelor_Room::where('id', $id)
        ->orderBy('id','desc')
        ->get();
        $comments=BechelorComment::all();
        //dd($bechelor_room);
        return view('Bechelor_room.index',compact('bechelor_room','comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities=City::all();
        return view('Bechelor_room.create',compact('cities'));
    }

    public function cities_ajax($id)
    {
        $Thanas=DB::table("Thanas")
        ->where("city_id",$id)
        ->pluck("thana","id");
        return json_encode($Thanas);
    }

    public function thanas_ajax($id)
    {
        $wards=DB::table("wards")
        ->where("thana_id",$id)
        ->pluck("ward","id");
        return json_encode($wards);
        

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input= $request->all();
        $input['user_id'] = Auth::user()->id;

        $input['facilities'] = implode(',', $input['facilities']);
        $input['conditions'] = implode(',', $input['conditions']);

        if(isset($input['image'])){
            $input['image'] = $this->upload($input['image']);
        }else{
            $input['image'] = 'image/default.jpg';
        }
        //dd($input);
        $user_id=$input['user_id'];

        $result=Bechelor_Room::create($input);
        if($result){
            return redirect()->to('bechelor_post/by_user_id/'.$user_id)->with('message','Create Successfully');
        }else{
            return beck()->with('message','Some Error Occar');
        }

    }

    public function upload($file){
        //$extension = $file->getClientOrginalExtension();
        $name =time().$file->getClientOriginalName();
        $filename=$name;
        $current = public_path('image_bechelor_room/');
        $file->move($current, $filename);
        return 'image_bechelor_room/'.$filename;
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $bechelor_room = Bechelor_Room::findOrFail($id);
        $comments=BechelorComment::all();
        return view('assistants.show',compact('bechelor_room','comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bechelor_rooms = Bechelor_Room::findOrFail($id);
        $facilities = explode(",", $bechelor_rooms->facilities);
        $conditions = explode(",", $bechelor_rooms->conditions);
        $cities=City::all();
        return view('bechelor_room.edit',compact('bechelor_rooms','cities','facilities','conditions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $bechelor_rooms = Bechelor_Room::findOrFail($id);
        $input =$request->all();
        if(isset($input['image'])){
            $input['image'] = $this->upload($input['image']);
        }
        $input['facilities'] = implode(',', $input['facilities']);
        $input['conditions'] = implode(',', $input['conditions']);
        $result=$bechelor_rooms->update($input);
        if($result){
            return redirect('bechelor_room')->with('message','Update Successfully');
        }else{
            return beck()->with('message','Some Error Occar');
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

Easy_finder/resources/views/Bechelor_room/index.blade.php
@extends('layouts.app')

@section('content')
@foreach($bechelor_room as $post)
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="box-title" style="text-align: center;font-size: 30px;color: white;background-color: #0321fd"><strong>{{$post->seat}} Roommate Wanted,From {{$post->date}} at {{$post->wards->ward}}</strong></h4>
                            </div>
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="row">
                                                    <div class="col-sm-4">
                                                        <h4><span>Type</span></h4>
                                                        <h4><span>Gender</span></h4>
                                                        <h4><span>Religion</span></h4>
                                                        <h4><span>Status</span></h4>
                                                        <h4><span>City</span></h4>
                                                        <h4><span>Thana</span></h4>
                                                        <h4><span>Contact</span></h4>
                                                    </div>
                                                    <div class="col-sm-8">
                                                        <h4><span>{{$post->status}}</span></h4>
                                                        <h4><span>{{$post->gender}}</span></h4>
                                                        <h4><span>{{$post->religion}}</span></h4>
                                                        <h4><span>{{$post->married}}</span></h4>
                                                        <h4><span>{{$post->cities->city}}</span></h4>
                                                        <h4><span>{{$post->thanas->thana}}</span></h4>
                                                        <h4><span>{{$post->mobile}}</span></h4>
                                                    </div>
                                                </div>
                                                <h4 style="padding-top: 20px"><strong>Addeess:</strong> <span>{{$post->address}}</span></h4>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="row">
                                                    <div class="col-sm-5">
                                                        <h4><span></span></h4>
                                                        <h4><span>Room</span></h4>
                                                        <h4><span>Room Type</span></h4>
                                                        <h4><span>Room Rent</span></h4>
                                                    </div>
                                                    <div class="col-sm-7">
                                                        <h4><span class="pull-right"><a href="{{route('bechelor.booking',$post->id)}}" class="btn btn-success btn-sm">Now book</a></span></h4>
                                                        <h4><span>{{$post->room}}</span></h4>
                                                        <h4><span>{{$post->room_type}}</span></h4>
                                                        <h4><span>{{$post->room_rent}}</span></h4>
                                                    </div>
                                                </div>
                                                <h4 style="padding-top: 20px"><strong>Facilities:</strong> <span>{{$post->facilities}}</span></h4>
                                                <h4 style="padding-top: 20px"><strong>Conditions:</strong> <span>{{$post->conditions}}</span></h4>
                                            </div>
                                        </div>
                                        <p style="padding-top: 20px"><span>Created By : <a href="{{route('user_details.show', $post->user->id)}}">{{$post->user->name}}</a></span> <span class="pull-right">Created at: {{$post->created_at->toFormattedDateString()}}</span></p>
                                        <div class="card-header">
                                                <h4><strong>Comments</strong></h4>
                                        </div>
                                            @foreach($comments as $comment)
                                                    @if($post->id==$comment->bechelor_comment_id)
                                                    <p style="color: green"><span><a href="{{route('user_details.show', $comment->user->id)}}"><span style="color: green;"><b>{{$comment->user->name}}</b></span></a></span><span class="pull-right">{{$comment->created_at->toFormattedDateString()}}</span></p>
                                                    <p>
                                                        <span>{{ $comment->body }}</span>
                                                        <span class="pull-right">
                                                            @if(Auth::user()->email==$comment->user->email)
                                                            <span><a href="{{route('comment.edit', $comment->id)}}"><i class="fa fa-pencil"></i></a></span>
                                                            @endif
                                                        </span> 
                                                    </p>
                                                    @endif
                                            @endforeach
                                        <!-- <h4>Add comment</h4> -->
                                        <form method="post" action="{{ route('comment.store') }}">
                                            {{ csrf_field()}}
                                            <input type="hidden" name="bechelor_comment_id" value="{{ $post->id }}" />
                                            <label for="body">Add Comment</label>
                                                <textarea name="body" id="body" class="form-control" cols="30" rows="5"></textarea>
                                                <p class="help-block">{{ ($errors->has('body')) ? $errors->first('body') : ''}}</p>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-warning" value="submit">Comment</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="card-body">
                                        @if($post->image!="")
                                        <div class="portfolio-item">
                                            <div class="portfolio-item-inner">
                                                <img class="img-responsive" src="{{asset($post->image)}}" alt="">
                                                    <div class="portfolio-info">
                                                        <a class="preview" href="{{asset($post->image)}}" rel="prettyPhoto"><i class="fa fa-eye"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        @endif
                                        @if(Auth::user()->email==$post->user->email)
                                        <p style="margin-top: 20px">
                                             <span class="btn btn-danger btn-sm"><a href="{{route('show_request.show_request', $post->id)}}" style="color: #fff"> Show Request</a></span>
                                            <span class="btn btn-warning pull-right"><a href="{{route('bechelor_room.edit', $post->id)}}" ><i class="fa fa-edit fa-lg" style="color: #fff"></i></a></span>
                                        </p>
                                        @endif
                                        <!-- <span class="pull-right"><a href="{{route('bechelor.booking',$post->id)}}" class="btn btn-primary btn-sm">Now book</a></span></p> -->
                                    </div>
                                </div>
                            </div>
                            <h4 style="text-align: center; color: green">===========Bechelor Roommate Wanted============</h4>
                            <div class="card-body"></div>
                        </div>
                    </div>
                </div>
                @endforeach
@endsection

Easy_finder/resources/views/Bechelor_room/search.blade.php
@extends('layouts.app')
@section('content')
  <script type="text/javascript" src="{{ url('')}}/assets/js/jquery-3.2.1.min.js"></script>
  <div class="content">
    <div class="animated fadeIn">
      <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 offset-xs-3 offset-sm-3 offset-md-3">
          @if((Session::get('message')))
          <div class="alert alert-success alert-dismissable">
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ Session::get('message')}}
            </div>
          </div>
          @endif
          <div class="card">
            <div class="card-header" style="text-align: center; background-color: #0321fd; color: #ffffff">
              <strong>Bechelor Room Create/Post Form</strong>
            </div>
            <div class="card-body card-block">
              <form role="form" action="{{ route('search_post.search_post')}}" method="post" enctype="multipart/form-data">
                {{ csrf_field()}}
                <div class="form-group">
                  <label for="city">Select City</label>
                  <select name="city" id="city" class="form-control">
                    <option value="0" disabled="true" selected="true">===Choose City==</option>
                    @foreach($cities as $city)
                    <option value="{{$city->id}}">{{$city->city}}</option>
                    @endforeach
                  </select>
                  <p class="help-block">{{ ($errors->has('city')) ? $errors->first('city') : ''}}</p>
                </div>
                <div class="form-group">
                  <label for="thana">Select Thana</label>
                  <select name="thana" id="thana" class="form-control">
                    <option value="0" disabled="true" selected="true">===Choose Thana==</option>
                  </select>
                  <p class="help-block">{{ ($errors->has('thana')) ? $errors->first('thana') : ''}}</p>
                </div>
                <div class="form-group">
                  <label for="ward">Select Ward</label>
                  <select name="ward" id="ward" class="form-control">
                    <option value="0" disabled="true" selected="true">===Choose Ward==</option>
                  </select>
                  <p class="help-block">{{ ($errors->has('ward')) ? $errors->first('ward') : ''}}</p>
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
              </form>
              <script type="text/javascript">
              $(document).ready(function(){
              $('select[name="city"]').on('change',function(){
              var cityid=$(this).val();
              if(cityid){
              $.ajax({
              url:'{{ url('')}}/cities/ajax/'+cityid,
              type:"GET",
              dataType:"json",
              success:function(data){
              $('select[name="thana"]').empty();
              $.each(data,function(key,value){
              $('select[name="thana"]').append('<option value="'+key+'">'+value+'</option>')
              });
              }
              });
              }else{
              $('select[name="thana"]').empty();
              }
              });
              $('select[name="thana"]').on('change',function(){
              var thanaid=$(this).val();
              console.log(thanaid);
              if(thanaid){
              $.ajax({
              url:'{{ url('')}}/thanas/ajax/'+thanaid,
              type:"GET",
              dataType:"json",
              success:function(data){
              $('select[name="ward"]').empty();
              $.each(data,function(key,value){
              $('select[name="ward"]').append('<option value="'+key+'">'+value+'</option>')
              });
              }
              });
              }else{
              $('select[name="ward"]').empty();
              }
              });
              });
              </script>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
@endsection

Easy_finder/resources/views/Bechelor_room/show.blade.php
@extends('layouts.app')

@section('content')
@foreach($bechelor_room as $post)
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="box-title" style="text-align: center;font-size: 30px;color: white;background-color: #0321fd"><strong>{{$post->seat}} Roommate Wanted,From {{$post->date}} at {{$post->wards->ward}}</strong></h4>
                            </div>
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="row">
                                                    <div class="col-sm-4">
                                                        <h4><span>Type</span></h4>
                                                        <h4><span>Gender</span></h4>
                                                        <h4><span>Religion</span></h4>
                                                        <h4><span>Status</span></h4>
                                                        <h4><span>City</span></h4>
                                                        <h4><span>Thana</span></h4>
                                                        <h4><span>Contact</span></h4>
                                                    </div>
                                                    <div class="col-sm-8">
                                                        <h4><span>{{$post->status}}</span></h4>
                                                        <h4><span>{{$post->gender}}</span></h4>
                                                        <h4><span>{{$post->religion}}</span></h4>
                                                        <h4><span>{{$post->married}}</span></h4>
                                                        <h4><span>{{$post->cities->city}}</span></h4>
                                                        <h4><span>{{$post->thanas->thana}}</span></h4>
                                                        <h4><span>{{$post->mobile}}</span></h4>
                                                    </div>
                                                </div>
                                                <h4 style="padding-top: 20px"><strong>Addeess:</strong> <span>{{$post->address}}</span></h4>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="row">
                                                    <div class="col-sm-5">
                                                        <h4><span></span></h4>
                                                        <h4><span>Room</span></h4>
                                                        <h4><span>Room Type</span></h4>
                                                        <h4><span>Room Rent</span></h4>
                                                    </div>
                                                    <div class="col-sm-7">
                                                        <h4><span class="pull-right"><a href="{{route('bechelor.booking',$post->id)}}" class="btn btn-success btn-sm">Now book</a></span></h4>
                                                        <h4><span>{{$post->room}}</span></h4>
                                                        <h4><span>{{$post->room_type}}</span></h4>
                                                        <h4><span>{{$post->room_rent}}</span></h4>
                                                    </div>
                                                </div>
                                                <h4 style="padding-top: 20px"><strong>Facilities:</strong> <span>{{$post->facilities}}</span></h4>
                                                <h4 style="padding-top: 20px"><strong>Conditions:</strong> <span>{{$post->conditions}}</span></h4>
                                            </div>
                                        </div>
                                        <p style="padding-top: 20px"><span>Created By : <a href="{{route('user_details.show', $post->user->id)}}">{{$post->user->name}}</a></span> <span class="pull-right">Created at: {{$post->created_at->toFormattedDateString()}}</span></p>
                                        <div class="card-header">
                                                <h4><strong>Comments</strong></h4>
                                        </div>
                                            @foreach($comments as $comment)
                                                    @if($post->id==$comment->bechelor_comment_id)
                                                    <p style="color: green"><span><a href="{{route('user_details.show', $comment->user->id)}}"><span style="color: green;"><b>{{$comment->user->name}}</b></span></a></span><span class="pull-right">{{$comment->created_at->toFormattedDateString()}}</span></p>
                                                    <p>
                                                        <span>{{ $comment->body }}</span>
                                                        <span class="pull-right">
                                                            @if(Auth::user()->email==$comment->user->email)
                                                            <span><a href="{{route('comment.edit', $comment->id)}}"><i class="fa fa-pencil"></i></a></span>
                                                            @endif
                                                        </span> 
                                                    </p>
                                                    @endif
                                            @endforeach
                                        <!-- <h4>Add comment</h4> -->
                                        <form method="post" action="{{ route('comment.store') }}">
                                            {{ csrf_field()}}
                                            <input type="hidden" name="bechelor_comment_id" value="{{ $post->id }}" />
                                            <label for="body">Add Comment</label>
                                                <textarea name="body" id="body" class="form-control" cols="30" rows="5"></textarea>
                                                <p class="help-block">{{ ($errors->has('body')) ? $errors->first('body') : ''}}</p>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-warning" value="submit">Comment</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="card-body">
                                        @if($post->image!="")
                                        <div class="portfolio-item">
                                            <div class="portfolio-item-inner">
                                                <img class="img-responsive" src="{{asset($post->image)}}" alt="">
                                                    <div class="portfolio-info">
                                                        <a class="preview" href="{{asset($post->image)}}" rel="prettyPhoto"><i class="fa fa-eye"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        @endif
                                        @if(Auth::user()->email==$post->user->email)
                                        <p style="margin-top: 20px">
                                             <span class="btn btn-danger btn-sm"><a href="{{route('show_request.show_request', $post->id)}}" style="color: #fff"> Show Request</a></span>
                                            <span class="btn btn-warning pull-right"><a href="{{route('bechelor_room.edit', $post->id)}}" ><i class="fa fa-edit fa-lg" style="color: #fff"></i></a></span>
                                        </p>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <h4 style="text-align: center; color: green">===========Bechelor Roommate Wanted============</h4>
                            <div class="card-body"></div>
                        </div>
                    </div>
                </div>
                @endforeach
@endsection